name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x']

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: |
        cd ReactSample
        dotnet restore 
      
    - name: Build
      run: |
        cd ReactSample
        dotnet build --no-restore
      
    - name: Test
      run: |
        cd ReactSample
        dotnet test --no-build --verbosity normal

    - name: Publish
      run: |
        cd ReactSample
        dotnet publish -c Release -o ./webapp-release -r linux-x64 --self-contained true /p:UseAppHost=true
        zip -9 -r -q react-app-linux-x64.zip ./webapp-release
        ls -la
        
    - name: Upload ReactApp as Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ReactApp
        path: react-app-linux-x64.zip
